5. Model & Utility Application Implementation/covid_prediction/ClientData/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('homepage/' , views.homepage, name="homepage"),
    path('ClientDataEntry/' , views.ClientDataEntry, name="ClientDataEntry"),
    path('Results/' , views.Results, name="Results"),
    path('Results/<prediction>/', views.Results, name='Results'),
]

5. Model & Utility Application Implementation/covid_prediction/covid_prediction/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("django.contrib.auth.urls")),
    # path('', include('ClientData.urls')),
    path('', RedirectView.as_view(url='/homepage/')),  # Redirect root URL to /homepage/
    path('', include('ClientData.urls')),
]

5. Model & Utility Application Implementation/covid_prediction/ClientData/models.py
from django.db import models

# Create your models here.

class COVID_DATA_ML(models.Model):
    USMER = models.BooleanField(default=False)
    SEX = models.BooleanField(default=False)
    PATIENT_TYPE = models.BooleanField(default=False)
    # DEAD = models.BooleanField(default=False)
    PNEUMONIA = models.BooleanField(default=False)
    AGE = models.IntegerField(default=0)
    PREGNANT = models.BooleanField(default=False)
    DIABETES = models.BooleanField(default=False)
    COPD = models.BooleanField(default=False)
    ASTHMA = models.BooleanField(default=False)
    INMSUPR = models.BooleanField(default=False)
    HIPERTENSION = models.BooleanField(default=False)
    OTHER_DISEASE = models.BooleanField(default=False)
    CARDIOVASCULAR = models.BooleanField(default=False)
    OBESITY = models.BooleanField(default=False)
    RENAL_CHRONIC = models.BooleanField(default=False)
    TOBACO = models.BooleanField(default=False)
    # Add fields for MEDICAL_UNIT_2 to MEDICAL_UNIT_13 as needed
    MEDICAL_UNIT_1 = models.BooleanField(default=False)
    MEDICAL_UNIT_2 = models.BooleanField(default=False)
    MEDICAL_UNIT_3 = models.BooleanField(default=False)
    MEDICAL_UNIT_4 = models.BooleanField(default=False)
    MEDICAL_UNIT_5 = models.BooleanField(default=False)
    MEDICAL_UNIT_6 = models.BooleanField(default=False)
    MEDICAL_UNIT_7 = models.BooleanField(default=False)
    MEDICAL_UNIT_8 = models.BooleanField(default=False)
    MEDICAL_UNIT_9 = models.BooleanField(default=False)
    MEDICAL_UNIT_10 = models.BooleanField(default=False)
    MEDICAL_UNIT_11 = models.BooleanField(default=False)
    MEDICAL_UNIT_12 = models.BooleanField(default=False)
    MEDICAL_UNIT_13 = models.BooleanField(default=False)
    CLASSIFICATION_FINAL = models.BooleanField(default=False)
    # GROUND_TRUTH = models.BooleanField(default=False)

5. Model & Utility Application Implementation/covid_prediction/ClientData/forms.py
from django import forms
from .models import COVID_DATA_ML

class COVIDDataForm(forms.ModelForm):
    class Meta:
        model = COVID_DATA_ML
        fields = '__all__'
    # Define choices for medical units
    MEDICAL_UNIT_CHOICES = [(i, f"Medical Unit {i}") for i in range(1, 14)]
    
    # Create ChoiceField for medical units
    medical_unit_choice = forms.ChoiceField(choices=MEDICAL_UNIT_CHOICES, widget=forms.Select(attrs={'class': 'form-select'}))
        # widgets = {
        #     'SEX': forms.CheckboxInput(choices=[('Male', 'Male'), ('Female', 'Female')]),
        # }

5. Model & Utility Application Implementation/covid_prediction/ClientData/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import COVIDDataForm
from .models import COVID_DATA_ML
from django.contrib import messages
from keras.models import model_from_json
from django.core.management.base import BaseCommand
from datetime import datetime
# from tensorflow.keras.models import load_model
import os
import zipfile
import numpy as np
import schedule
import time

def preprocess_row2(row):
    input_values = [
        row['USMER'], 
        row['SEX'], 
        row['PATIENT_TYPE'], 
        # 0,                  # will be removed for the dead part. 
        row['PNEUMONIA'], 
        row['AGE'], 
        row['PREGNANT'], 
        row['DIABETES'], 
        row['COPD'], 
        row['ASTHMA'], 
        row['INMSUPR'], 
        row['HIPERTENSION'], 
        row['OTHER_DISEASE'], 
        row['CARDIOVASCULAR'], 
        row['OBESITY'], 
        row['RENAL_CHRONIC'], 
        row['TOBACO'], 
        row['MEDICAL_UNIT_1'], 
        row['MEDICAL_UNIT_2'], 
        row['MEDICAL_UNIT_3'], 
        row['MEDICAL_UNIT_4'], 
        row['MEDICAL_UNIT_5'], 
        row['MEDICAL_UNIT_6'], 
        row['MEDICAL_UNIT_7'], 
        row['MEDICAL_UNIT_8'], 
        row['MEDICAL_UNIT_9'], 
        row['MEDICAL_UNIT_10'], 
        row['MEDICAL_UNIT_11'], 
        row['MEDICAL_UNIT_12'], 
        row['MEDICAL_UNIT_13'],
        # row[medical_unit_choice],
    ]
    return input_values
def preprocess_row1(data): 
    
    row = {
            'USMER' :0 if data['USMER'] == False else 1,
            'SEX' :0 if data['SEX'] == False else 1,
            'PATIENT_TYPE' :0 if data['PATIENT_TYPE'] == False else 1,
            # 'DEAD' :0 if data['DEAD'] == False else 1,
            'PNEUMONIA' :0 if data['PNEUMONIA'] == False else 1,
            'AGE' :data['AGE'],
            'PREGNANT' :0 if data['PREGNANT'] == False else 1,
            'DIABETES' :0 if data['DIABETES'] == False else 1,
            'COPD' :0 if data['COPD'] == False else 1,
            'ASTHMA' :0 if data['ASTHMA'] == False else 1,
            'INMSUPR' :0 if data['INMSUPR'] == False else 1,
            'HIPERTENSION' :0 if data['HIPERTENSION'] == False else 1,
            'OTHER_DISEASE' :0 if data['OTHER_DISEASE'] == False else 1,
            'CARDIOVASCULAR' :0 if data['CARDIOVASCULAR'] == False else 1,
            'OBESITY' :0 if data['OBESITY'] == False else 1,
            'RENAL_CHRONIC' :0 if data['RENAL_CHRONIC'] == False else 1,
            'TOBACO' :0 if data['TOBACO'] == False else 1,
            'MEDICAL_UNIT_1' :0 if data['MEDICAL_UNIT_1'] == False else 1,
            'MEDICAL_UNIT_2' :0 if data['MEDICAL_UNIT_2'] == False else 1,
            'MEDICAL_UNIT_3' :0 if data['MEDICAL_UNIT_3'] == False else 1,
            'MEDICAL_UNIT_4' :0 if data['MEDICAL_UNIT_4'] == False else 1,
            'MEDICAL_UNIT_5' :0 if data['MEDICAL_UNIT_5'] == False else 1,
            'MEDICAL_UNIT_6' :0 if data['MEDICAL_UNIT_6'] == False else 1,
            'MEDICAL_UNIT_7' :0 if data['MEDICAL_UNIT_7'] == False else 1,
            'MEDICAL_UNIT_8' :0 if data['MEDICAL_UNIT_8'] == False else 1,
            'MEDICAL_UNIT_9' :0 if data['MEDICAL_UNIT_9'] == False else 1,
            'MEDICAL_UNIT_10' :0 if data['MEDICAL_UNIT_10'] == False else 1,
            'MEDICAL_UNIT_11' :0 if data['MEDICAL_UNIT_11'] == False else 1,
            'MEDICAL_UNIT_12' :0 if data['MEDICAL_UNIT_12'] == False else 1,
            'MEDICAL_UNIT_13' :0 if data['MEDICAL_UNIT_13'] == False else 1,
            # medicalchoice:1,
        }
            
    # print ("&&&&&&&&&&&&&-----&&&&&&&&&&&&&&&")
    # print ("row: ", row)
    # input_values = preprocess_row2(row)
    return row


def prepreprocess(data):
    row = {
        'USMER' : 0 if data.USMER == False else 1,
        'SEX' : 0 if data.SEX == False else 1,
        'PATIENT_TYPE' : 0 if data.PATIENT_TYPE == False else 1,
        # 'DEAD' :0 if data['DEAD'] == False else 1,
        'PNEUMONIA' : 0 if data.PNEUMONIA == False else 1,
        'AGE' : data.AGE,
        'PREGNANT' : 0 if data.PREGNANT == False else 1,
        'DIABETES' : 0 if data.DIABETES == False else 1,
        'COPD' : 0 if data.COPD == False else 1,
        'ASTHMA' : 0 if data.ASTHMA == False else 1,
        'INMSUPR' : 0 if data.INMSUPR == False else 1,
        'HIPERTENSION' : 0 if data.HIPERTENSION == False else 1,
        'OTHER_DISEASE' : 0 if data.OTHER_DISEASE == False else 1,
        'CARDIOVASCULAR' : 0 if data.CARDIOVASCULAR == False else 1,
        'OBESITY' : 0 if data.OBESITY == False else 1,
        'RENAL_CHRONIC' : 0 if data.RENAL_CHRONIC == False else 1,
        'TOBACO' : 0 if data.TOBACO == False else 1,
        'MEDICAL_UNIT_1' : 0 if data.MEDICAL_UNIT_1 == False else 1,
        'MEDICAL_UNIT_2' : 0 if data.MEDICAL_UNIT_2 == False else 1,
        'MEDICAL_UNIT_3' : 0 if data.MEDICAL_UNIT_3 == False else 1,
        'MEDICAL_UNIT_4' : 0 if data.MEDICAL_UNIT_4 == False else 1,
        'MEDICAL_UNIT_5' : 0 if data.MEDICAL_UNIT_5 == False else 1,
        'MEDICAL_UNIT_6' : 0 if data.MEDICAL_UNIT_6 == False else 1,
        'MEDICAL_UNIT_7' : 0 if data.MEDICAL_UNIT_7 == False else 1,
        'MEDICAL_UNIT_8' : 0 if data.MEDICAL_UNIT_8 == False else 1,
        'MEDICAL_UNIT_9' : 0 if data.MEDICAL_UNIT_9 == False else 1,
        'MEDICAL_UNIT_10' : 0 if data.MEDICAL_UNIT_10 == False else 1,
        'MEDICAL_UNIT_11' : 0 if data.MEDICAL_UNIT_11 == False else 1,
        'MEDICAL_UNIT_12' : 0 if data.MEDICAL_UNIT_12 == False else 1,
        'MEDICAL_UNIT_13' : 0 if data.MEDICAL_UNIT_13 == False else 1,
        # medicalchoice:1,
    }
    return preprocess_row2(row)

def retrain_at_midnight(data):
    print("In retraining")
    model_path = './AI_models/FinalModel'
    model = load_model_from_files(model_path)
    print(type(data))
    print(type(data[0]))
    x_train = [row[:-1] for row in data]  
    y_train = [row[-1] for row in data]   
    x_train = np.array(x_train)
    y_train = np.array(y_train).reshape(-1, 1)
    model.fit(x_train, y_train)
    model.save("Model.keras") #to save the model params
    print("New model saved")


def schedule_retraining():
    min_entires = 2048  # Adjust this value as needed
    num_entries = COVID_DATA_ML.objects.count()
    all_entries = COVID_DATA_ML.objects.all()
    print("-------------_________--------------")
    data_to_train = []
    current_time = datetime.now().time()
        # Check if it's the desired time (e.g., 12:00 AM)
    if current_time.hour == 8:
        print("It is going to retraiiiin")
        for i in range(num_entries):
            entry = all_entries[i]
            row = prepreprocess(entry)
            row.append(entry.CLASSIFICATION_FINAL)
            data_to_train.append(row)

        print("Done adding")
        # schedule.every().day.at("00:00").do(retrain_at_midnight(data_to_train))
        retrain_at_midnight(data_to_train)

    # for entry in all_entries:
    #     # print(entry.USMER)
    #     # print(type(entry))
    #     # print(type(entry.USMER))
    #     # data1 = prepreprocess(entry)
    #     data_to_train.append(prepreprocess(entry))

    # print(type(all_entries[0]))
    # if num_entries > min_entires:
    #     # print("Number of entries exceeds the maximum.")
    #     x=0
    # else:
    #     x=0
    #     # print("Number of entries is within the limit.")
    #     # Perform actions if the number of entries is within the limit

    # schedule.every().day.at("00:00").do(retrain_at_midnight)

    # Run the scheduler loop
    # while True:
    #     schedule.run_pending()
    #     time.sleep(1)  # Sleep for 1 second to prevent high CPU usage

# Call the scheduling function when your Django server starts
# schedule_retraining()






# def retrain() :
#     all_entries = COVID_DATA_ML.objects.all()
# # @staff_member_required
# def retrain_model(request):
#     if request.method == 'POST':
#         form = RetrainForm(request.POST)
#         if form.is_valid():
#             # Load the dataset saved from user data
#             dataset = load_dataset()
#             # Preprocess the dataset
#             X_train, y_train = preprocess_data(dataset)
#             # Train the model
#             new_model = train_model(X_train, y_train)
#             # Save the updated model
#             new_model.save('path/to/updated_model')
#             return render(request, 'retrain_success.html')
#     else:
#         form = RetrainForm()
#     return render(request, 'retrain_form.html', {'form': form})


def load_model_from_files(model_path):
    # Load model architecture from JSON file
    with open(os.path.join(model_path, 'config.json'), 'r') as json_file:
        model_json = json_file.read()
        model = model_from_json(model_json)

    # Load model weights
    model.load_weights(os.path.join(model_path, 'model.weights.h5'))
    return model



def make_prediction(form_data):
    model_path = './AI_models/FinalModel'

    model = load_model_from_files(model_path)
    sample = np.array([form_data])
    prediction = model.predict(sample)
    print ("------------------>>>>>>>",prediction)
    if(prediction[0] >=0.47):
        ans = True
    else: ans = False
    # prediction = True
    
    return ans





def ClientDataEntry(request):
    if request.method == 'POST':
        form = COVIDDataForm(request.POST)
        if form.is_valid():
            # Print form values to console
            # print("Form data before saving:", form.cleaned_data)

            # Get selected medical unit
            medical_unit = int(form.cleaned_data['medical_unit_choice'])
            medicalchoice = f"MEDICAL_UNIT_{medical_unit}"
            input_values = preprocess_row1(form.cleaned_data)
            input_values["MEDICAL_UNIT_{medical_unit}"]=1
            input_values = preprocess_row2(input_values)
            # input_values = {}
            
            # medical_unit = int(data['medical_unit_choice'])

5. Model & Utility Application Implementation/covid_prediction/ClientData/templates/ClientDataForm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.0.0/css/bootstrap.rtl.min.css" integrity="sha512-+IhzrT1JyXRxWuvzHykmn+RE1wXuw9sjSAmBBKnN4fRqlqwX9tTXmWPlHqOpbOyEPX3a4W8SEDwDbHJSYTO3aQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <title>Document</title>

</head>
<body>
    <!-- <button class="btn btn-primary"> everything is here. </button> -->
    <h1 class=" bg-secondary shadow  w-100 text-center border border-bold mt-2 p-3 " style="height: 10%; color: darkblue;">Client Data Entry Form</h1>
    <div class="container border-primary w-100 d-flex align-items-center align-self-center" style="height: 80%">
        <!-- <form method="post" class = "border border-secondary">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Submit</button>
        </form> -->
        <form method="post">
            {% csrf_token %}
            {% if form.errors %}
                <div class="alert alert-danger">
                    <strong>Error!</strong> Please correct the following errors:<br>
                    {{ form.errors }}
                </div>
            {% endif %}
            
            <!--  -->
            <!--  -->
            <!-- Some personal information -->
            <div class="container d-flex flex-row justify-content-around flex-wrap border-bottom border-primary p-2 my-2">
                <p class="w-100 text-center fw-bolder">Personal Information </p>
                
                <!-- SEX -->
                <div>
                        <label>Patient Sex:</label><br>
                        <label>
                    <input type="radio" name="SEX" value="True" checked id="maleRadio"> Male
                    </label><br>
                    <label>
                    <input type="radio" name="SEX" value="False" id="femaleRadio"> Female
                    </label>
                </div>
            
            
                <!-- AGE -->
                <div>
                <label for="id_AGE">AGE:</label>
                {{ form.AGE }}
                </div>
            
                <!-- PREGNANT -->
                <div>
                    <label for="id_PREGNANT">PREGNANT:</label>
                    {{ form.PREGNANT }}
                </div>
            
            </div>


            <!--  -->
            <!--  -->
            <!-- medical care recieved by the patient -->
            <div class="container d-flex flex-column justify-content-around align-items-center flex-wrap border-bottom border-primary p-2 my-2">
                <p class="w-100 text-center fw-bolder">Care recieved </p>
                
                <!-- USMER -->
                <div class="my-3">
                    <label>What level of medical care did the patient receive (USMER): </label><br>
                    <label>
                    <input type="radio" name="USMER" value="False" checked> First-level (the initial point of contact between individuals and the healthcare system)
                    </label><br>
                    <label>
                    <input type="radio" name="USMER" value="True"> Second-level (involves more specialized services than primary care)
                    </label>
                </div>

                 <!-- PATIENT TYPE -->
                <div class="my-3">
                    <label>type of care the patient received in the unit. </label><br>
                    <label>
                    <input type="radio" name="PATIENT_TYPE" value="True" checked> hospitalized (0) <!-- 0 for hospitalization -->
                    </label><br>
                    <label>
                    <input type="radio" name="PATIENT_TYPE" value="False"> returned home (1) <!-- 1 for returned home-->
                    </label>
                </div>

                <div class="mb-3 my-3">
                    <!-- <label for="medical_unit" class="form-label">Select Medical Unit</label> -->
                    <label for="medical_unit_choice" class="form-label">Select type of institution of the National Health System that provided the care.</label>
                    <!-- <select id="medical_unit" name="medical_unit" class="form-select"> -->
                    <select id="medical_unit_choice" name="medical_unit_choice" class="form-select">
                        <option value="1" >Medical Unit 1  General Hospital</option>
                        <option value="2" >Medical Unit 2  Community Health Center</option>
                        <option value="3" >Medical Unit 3  Specialty Clinic</option>
                        <option value="4" >Medical Unit 4  Rehabilitation Center</option>
                        <option value="5" >Medical Unit 5  Mental Health Facility</option>
                        <option value="6" >Medical Unit 6  Outpatient Surgery Center</option>
                        <option value="7" >Medical Unit 7  Urgent Care Center</option>
                        <option value="8" >Medical Unit 8  Long-Term Care Facility</option>
                        <option value="9" >Medical Unit 9  Maternity Hospital</option>
                        <option value="10">Medical Unit 10 Pediatric Clinic</option>
                        <option value="11">Medical Unit 11 Cancer Treatment Center</option>
                        <option value="12">Medical Unit 12 Cardiac Care Unit</option>
                        <option value="13">Medical Unit 13 Infectious Disease Center</option>
                        <!-- Add options for Medical Unit 4 to Medical Unit 13 here -->
                    </select>
                </div>
                
                <!-- DEAD -->
                <!-- <div>
                    <label for="id_DEAD">Did the patient die:</label>
                    {{ form.DEAD }}
                </div> -->
            </div>
            
            <div class="container d-flex flex-row justify-content-around flex-wrap border-bottom border-primary p-2 my-2 w-50">
                <p class="w-100 text-center fw-bolder">Check all the diseases that the patient suffered from </p>
                <!-- <div> -->
                <!-- PNEUMONIA -->
                <div class="m-2">
                    <label for="id_PNEUMONIA">PNEUMONIA:</label>
                    {{ form.PNEUMONIA }}
                </div>

                <!-- DIABETES -->
                <div class="m-2">
                    <label for="id_DIABETES">DIABETES:</label>
                    {{ form.DIABETES }}
                </div>
            
                <!-- COPD -->
                <div class="m-2">
                    <label for="id_COPD">COPD:</label>
                    {{ form.COPD }}
                </div>
            
                <!-- ASTHMA -->
                <div class="m-2">
                    <label for="id_ASTHMA">ASTHMA:</label>
                    {{ form.ASTHMA }}
                </div>
            
                <!-- INMSUPR -->
                <div class="m-2">
                    <label for="id_INMSUPR">INMSUPR:</label>
                    {{ form.INMSUPR }}
                </div>
            
                <!-- HIPERTENSION -->
                <div class="m-2">
                    <label for="id_HIPERTENSION">HIPERTENSION:</label>
                    {{ form.HIPERTENSION }}
                </div>
            
                <!-- OTHER DISEASE -->
                <div class="m-2">
                    <label for="id_OTHER_DISEASE">OTHER DISEASE:</label>
                    {{ form.OTHER_DISEASE }}
                </div>
            
                <!-- CARDIOVASCULAR -->
                <div class="m-2">
                    <label for="id_CARDIOVASCULAR">CARDIOVASCULAR:</label>
                    {{ form.CARDIOVASCULAR }}
                </div>
            
                <!-- OBESITY -->
                <div class="m-2">
                    <label for="id_OBESITY">OBESITY:</label>
                    {{ form.OBESITY }}
                </div>
            
                <!-- RENAL CHRONIC -->
                <div class="m-2">
                    <label for="id_RENAL_CHRONIC">RENAL CHRONIC:</label>
                    {{ form.RENAL_CHRONIC }}
                </div>
            </div>

            <div class="container d-flex flex-row justify-content-around flex-wrap border-bottom border-primary p-2 my-2">
                <p class="w-100 text-center fw-bolder">Additional Info </p>
                <!-- TOBACO -->
                <div>
                <label for="id_TOBACO">Does the patient Smokes Tobaco:</label>
                {{ form.TOBACO }}
                </div>
            </div>
        
            
  
        
            <!-- CLASSIFICATION FINAL -->
            <!-- <div>
              <label for="id_CLASSIFICATION_FINAL">CLASSIFICATION FINAL:</label>
              {{ form.CLASSIFICATION_FINAL }}
            </div> -->
            <!-- <div class="w-100 border border-primary mx-auto">
                    <button type="submit" class="mx-auto mb-4 w-25 btn bg-primary fw-bolder" style="color:white;">Submit</button>
            </div> -->
            <div class="w-100 mx-auto mb-4 ">
                <div class="d-flex justify-content-center">
                    <button type="submit" class=" mt-2 btn bg-primary fw-bolder w-25" style="color:white;">Submit</button>
                </div>
            </div>
          </form>
    </div>
    
    <script>
        // Get references to the radio buttons and the pregnant checkbox
        const maleRadio = document.getElementById('maleRadio');
        const femaleRadio = document.getElementById('femaleRadio');
        const pregnantCheckbox = document.getElementById('id_PREGNANT'); // Manually set the ID of the checkbox
        // Disable the "PREGNANT" checkbox
        window.addEventListener('DOMContentLoaded', function () {
            document.getElementById('id_PREGNANT').disabled = true;
        });

        // Add event listener to the radio buttons
        maleRadio.addEventListener('change', function () {
            if (this.checked) {
                // Disable the pregnant checkbox if male is selected
                console.log('Male radio button is checked');
                pregnantCheckbox.disabled = true;
                pregnantCheckbox.checked = false; // Uncheck the checkbox if it was checked
            }
        });

        femaleRadio.addEventListener('change', function () {
            if (this.checked) {
                // Enable the pregnant checkbox if female is selected
                console.log('Female is checked');
                pregnantCheckbox.disabled = false;
            }
        });
    </script>

</body>
</html>

5. Model & Utility Application Implementation/covid_prediction/ClientData/templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.0.0/css/bootstrap.rtl.min.css" integrity="sha512-+IhzrT1JyXRxWuvzHykmn+RE1wXuw9sjSAmBBKnN4fRqlqwX9tTXmWPlHqOpbOyEPX3a4W8SEDwDbHJSYTO3aQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <title>Document</title>
</head>
<body>
    <!-- <div class="container align-self-center "></div> -->
    <div class="container w-100 text-center mx-auto m-2 p-2 border-secondary fw-bolder text-primary mt-3 border-bottom">
        <h2 class="align-self-center ">Covid Prediction website</h2>
        <!-- Covid Prediction -->
    </div>
    <div class="container-fluid d-flex flex-row justify-content-around border-secondary align-items-center p-5" style="height: 70vh">
        <div id="text_part" style="width: 40%;">
            <p class="fw-bolder fs-4" > 
                For people who have symptoms similar to Covid-19 
            </p >
            <p class ="" style="font-size: 12px;">
                If you think you have Covid symptoms and you want to check whether you have covid or not please click on the button to the side and fill in the form to see a predictoin of almost 85% accuracy to your specific case
            </p>
                
                
            
        </div>
        <div class="container-fluid d-flex flex-column justify-content-around border-secondary align-items-center w-50">
            <a href="{% url 'ClientDataEntry' %}" class="button btn btn-primary m-3" style="height: 10%;">Predict My Covido State</a>
            <!-- <a href="{% url 'ClientDataEntry' %}" class="button btn btn-outline-warning m-3" style="height: 10%;">Retrain</a> -->
        </div>
    </div>
    
    
</body>
</html>